/* config-taglib.h. Generated by cmake from config-taglib.h.cmake */

/* Define if you have libz */
/* #undef HAVE_ZLIB */

/* #undef NO_ITUNES_HACKS */
#define   WITH_ASF 1
#define   WITH_MP4 1

#define TESTS_DIR "/home/ddt/Documents/VLC0924/android/vlc/contrib/android/taglib/tests/"

